### ISSUE TITLE
Feature Request: Display on survey completion page

### ISSUE THREAD

**Issue by jgardner-qha** [lsgs/redcap-instance-table#28]
First, I love this plugin!

I would really like to display a table of repeating instances on the survey completion page, particularly on a survey that submits repeating instances. This would allow someone completing the survey to easily see their progress while adding multiple repeating instances. If you'd like more information about what I'm looking for, please let me know. I'm not an experienced PHP programmer but I do dabble and may be able to contribute if needed.

**Comment by tristakop** [comment]
Yes, this suggestion sounds like a good time @jgardner-qha

**Comment by lsgs** [comment]
It's a good idea, but complicated by the fact that the survey page hooks (`redcap_survey_page_top` and `redcap_survey_page`) do not get called on the acknowledgement page, although the `redcap_every_page_top` hook could be used with some logic to only cal the function if the page happens to be a survey acknowledgement page. 

The other issue is how and where to specify the @INSTANCETABLE tag. Currently it operates from the field annotation of descriptive text fields, but there can be none of these on the acknowledgement page. 

I think the best way to achieve what you want would be to have a subsequent survey containing only the instance table that you auto-continue to instead of showing the acknowledgement text.
